// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/mudule2email.proto

package com.linlazy.mmorpg.pb;

public final class PBModule2Email {
  private PBModule2Email() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *客户端指令
   * </pre>
   *
   * Protobuf enum {@code EmailClientCmd}
   */
  public enum EmailClientCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EmailClientCmd_NONE = 0;</code>
     */
    EmailClientCmd_NONE(0),
    /**
     * <pre>
     *删除邮件
     * </pre>
     *
     * <code>Email_Delete = 1;</code>
     */
    Email_Delete(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EmailClientCmd_NONE = 0;</code>
     */
    public static final int EmailClientCmd_NONE_VALUE = 0;
    /**
     * <pre>
     *删除邮件
     * </pre>
     *
     * <code>Email_Delete = 1;</code>
     */
    public static final int Email_Delete_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EmailClientCmd valueOf(int value) {
      return forNumber(value);
    }

    public static EmailClientCmd forNumber(int value) {
      switch (value) {
        case 0: return EmailClientCmd_NONE;
        case 1: return Email_Delete;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmailClientCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EmailClientCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmailClientCmd>() {
            public EmailClientCmd findValueByNumber(int number) {
              return EmailClientCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule2Email.getDescriptor().getEnumTypes().get(0);
    }

    private static final EmailClientCmd[] VALUES = values();

    public static EmailClientCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EmailClientCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EmailClientCmd)
  }

  /**
   * <pre>
   *服务端指令
   * </pre>
   *
   * Protobuf enum {@code EmailServerCmd}
   */
  public enum EmailServerCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EmailServerCmd_NONE = 0;</code>
     */
    EmailServerCmd_NONE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EmailServerCmd_NONE = 0;</code>
     */
    public static final int EmailServerCmd_NONE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EmailServerCmd valueOf(int value) {
      return forNumber(value);
    }

    public static EmailServerCmd forNumber(int value) {
      switch (value) {
        case 0: return EmailServerCmd_NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmailServerCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EmailServerCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmailServerCmd>() {
            public EmailServerCmd findValueByNumber(int number) {
              return EmailServerCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule2Email.getDescriptor().getEnumTypes().get(1);
    }

    private static final EmailServerCmd[] VALUES = values();

    public static EmailServerCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EmailServerCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EmailServerCmd)
  }

  /**
   * <pre>
   *内部通信指令
   * </pre>
   *
   * Protobuf enum {@code EmailInternalCmd}
   */
  public enum EmailInternalCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EmailInternalCmd_NONE = 0;</code>
     */
    EmailInternalCmd_NONE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EmailInternalCmd_NONE = 0;</code>
     */
    public static final int EmailInternalCmd_NONE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EmailInternalCmd valueOf(int value) {
      return forNumber(value);
    }

    public static EmailInternalCmd forNumber(int value) {
      switch (value) {
        case 0: return EmailInternalCmd_NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmailInternalCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EmailInternalCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmailInternalCmd>() {
            public EmailInternalCmd findValueByNumber(int number) {
              return EmailInternalCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule2Email.getDescriptor().getEnumTypes().get(2);
    }

    private static final EmailInternalCmd[] VALUES = values();

    public static EmailInternalCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EmailInternalCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EmailInternalCmd)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/mudule2email.proto*;\n\016EmailClien" +
      "tCmd\022\027\n\023EmailClientCmd_NONE\020\000\022\020\n\014Email_D" +
      "elete\020\001*)\n\016EmailServerCmd\022\027\n\023EmailServer" +
      "Cmd_NONE\020\000*-\n\020EmailInternalCmd\022\031\n\025EmailI" +
      "nternalCmd_NONE\020\000B\'\n\025com.linlazy.mmorpg." +
      "pbB\016PBModule2Emailb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
