// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/mudule1chat.proto

package com.linlazy.mmorpg.pb;

public final class PBModule1Chat {
  private PBModule1Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *客户端指令
   * </pre>
   *
   * Protobuf enum {@code ClientCmd}
   */
  public enum ClientCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ChatClientCmd_NONE = 0;</code>
     */
    ChatClientCmd_NONE(0),
    /**
     * <pre>
     *发送聊天
     * </pre>
     *
     * <code>ChatClientCmd_SendChat = 1;</code>
     */
    ChatClientCmd_SendChat(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ChatClientCmd_NONE = 0;</code>
     */
    public static final int ChatClientCmd_NONE_VALUE = 0;
    /**
     * <pre>
     *发送聊天
     * </pre>
     *
     * <code>ChatClientCmd_SendChat = 1;</code>
     */
    public static final int ChatClientCmd_SendChat_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientCmd valueOf(int value) {
      return forNumber(value);
    }

    public static ClientCmd forNumber(int value) {
      switch (value) {
        case 0: return ChatClientCmd_NONE;
        case 1: return ChatClientCmd_SendChat;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientCmd>() {
            public ClientCmd findValueByNumber(int number) {
              return ClientCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientCmd[] VALUES = values();

    public static ClientCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClientCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ClientCmd)
  }

  /**
   * <pre>
   *服务端指令
   * </pre>
   *
   * Protobuf enum {@code ChatServerCmd}
   */
  public enum ChatServerCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ChatServerCmd_NONE = 0;</code>
     */
    ChatServerCmd_NONE(0),
    /**
     * <pre>
     *推送聊天
     * </pre>
     *
     * <code>ChatServerCmd_PushChat = 1;</code>
     */
    ChatServerCmd_PushChat(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ChatServerCmd_NONE = 0;</code>
     */
    public static final int ChatServerCmd_NONE_VALUE = 0;
    /**
     * <pre>
     *推送聊天
     * </pre>
     *
     * <code>ChatServerCmd_PushChat = 1;</code>
     */
    public static final int ChatServerCmd_PushChat_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChatServerCmd valueOf(int value) {
      return forNumber(value);
    }

    public static ChatServerCmd forNumber(int value) {
      switch (value) {
        case 0: return ChatServerCmd_NONE;
        case 1: return ChatServerCmd_PushChat;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatServerCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatServerCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatServerCmd>() {
            public ChatServerCmd findValueByNumber(int number) {
              return ChatServerCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.getDescriptor().getEnumTypes().get(1);
    }

    private static final ChatServerCmd[] VALUES = values();

    public static ChatServerCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatServerCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ChatServerCmd)
  }

  /**
   * <pre>
   *内部通信指令
   * </pre>
   *
   * Protobuf enum {@code InternalCmd}
   */
  public enum InternalCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>InternalCmd_NONE = 0;</code>
     */
    InternalCmd_NONE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>InternalCmd_NONE = 0;</code>
     */
    public static final int InternalCmd_NONE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InternalCmd valueOf(int value) {
      return forNumber(value);
    }

    public static InternalCmd forNumber(int value) {
      switch (value) {
        case 0: return InternalCmd_NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InternalCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InternalCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InternalCmd>() {
            public InternalCmd findValueByNumber(int number) {
              return InternalCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.getDescriptor().getEnumTypes().get(2);
    }

    private static final InternalCmd[] VALUES = values();

    public static InternalCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private InternalCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InternalCmd)
  }

  public interface ReqSendChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqSendChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *聊天类型 ，私聊，世界，系统，公会，组队，附近
     * </pre>
     *
     * <code>optional int32 chatType = 1;</code>
     */
    int getChatType();

    /**
     * <code>optional string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 扩展字段
     * 私聊 targetId 私聊目标
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    java.lang.String getExt();
    /**
     * <pre>
     * 扩展字段
     * 私聊 targetId 私聊目标
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    com.google.protobuf.ByteString
        getExtBytes();
  }
  /**
   * Protobuf type {@code ReqSendChat}
   */
  public  static final class ReqSendChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqSendChat)
      ReqSendChatOrBuilder {
    // Use ReqSendChat.newBuilder() to construct.
    private ReqSendChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqSendChat() {
      chatType_ = 0;
      content_ = "";
      ext_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReqSendChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              chatType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ext_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_ReqSendChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_ReqSendChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.class, com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.Builder.class);
    }

    public static final int CHATTYPE_FIELD_NUMBER = 1;
    private int chatType_;
    /**
     * <pre>
     *聊天类型 ，私聊，世界，系统，公会，组队，附近
     * </pre>
     *
     * <code>optional int32 chatType = 1;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object ext_;
    /**
     * <pre>
     * 扩展字段
     * 私聊 targetId 私聊目标
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 扩展字段
     * 私聊 targetId 私聊目标
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatType_ != 0) {
        output.writeInt32(1, chatType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (!getExtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ext_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chatType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (!getExtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ext_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat)) {
        return super.equals(obj);
      }
      com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat other = (com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat) obj;

      boolean result = true;
      result = result && (getChatType()
          == other.getChatType());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getExt()
          .equals(other.getExt());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqSendChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqSendChat)
        com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_ReqSendChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_ReqSendChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.class, com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.Builder.class);
      }

      // Construct using com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chatType_ = 0;

        content_ = "";

        ext_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_ReqSendChat_descriptor;
      }

      public com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat getDefaultInstanceForType() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.getDefaultInstance();
      }

      public com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat build() {
        com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat buildPartial() {
        com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat result = new com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat(this);
        result.chatType_ = chatType_;
        result.content_ = content_;
        result.ext_ = ext_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat) {
          return mergeFrom((com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat other) {
        if (other == com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat.getDefaultInstance()) return this;
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getExt().isEmpty()) {
          ext_ = other.ext_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int chatType_ ;
      /**
       * <pre>
       *聊天类型 ，私聊，世界，系统，公会，组队，附近
       * </pre>
       *
       * <code>optional int32 chatType = 1;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <pre>
       *聊天类型 ，私聊，世界，系统，公会，组队，附近
       * </pre>
       *
       * <code>optional int32 chatType = 1;</code>
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *聊天类型 ，私聊，世界，系统，公会，组队，附近
       * </pre>
       *
       * <code>optional int32 chatType = 1;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ext_ = "";
      /**
       * <pre>
       * 扩展字段
       * 私聊 targetId 私聊目标
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public java.lang.String getExt() {
        java.lang.Object ref = ext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 targetId 私聊目标
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        java.lang.Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 targetId 私聊目标
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public Builder setExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ext_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 targetId 私聊目标
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public Builder clearExt() {
        
        ext_ = getDefaultInstance().getExt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 targetId 私聊目标
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ext_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ReqSendChat)
    }

    // @@protoc_insertion_point(class_scope:ReqSendChat)
    private static final com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat();
    }

    public static com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqSendChat>
        PARSER = new com.google.protobuf.AbstractParser<ReqSendChat>() {
      public ReqSendChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqSendChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqSendChat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqSendChat> getParserForType() {
      return PARSER;
    }

    public com.linlazy.mmorpg.pb.PBModule1Chat.ReqSendChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PushChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *聊天类型 ，私聊，世界，系统，公会，组队，附近
     * </pre>
     *
     * <code>optional int32 chatType = 1;</code>
     */
    int getChatType();

    /**
     * <code>optional string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 扩展字段
     * 私聊 sourceId 消息来源 
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    java.lang.String getExt();
    /**
     * <pre>
     * 扩展字段
     * 私聊 sourceId 消息来源 
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    com.google.protobuf.ByteString
        getExtBytes();
  }
  /**
   * <pre>
   *推送聊天信息
   * </pre>
   *
   * Protobuf type {@code PushChat}
   */
  public  static final class PushChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PushChat)
      PushChatOrBuilder {
    // Use PushChat.newBuilder() to construct.
    private PushChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushChat() {
      chatType_ = 0;
      content_ = "";
      ext_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PushChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              chatType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ext_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_PushChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_PushChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.class, com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.Builder.class);
    }

    public static final int CHATTYPE_FIELD_NUMBER = 1;
    private int chatType_;
    /**
     * <pre>
     *聊天类型 ，私聊，世界，系统，公会，组队，附近
     * </pre>
     *
     * <code>optional int32 chatType = 1;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object ext_;
    /**
     * <pre>
     * 扩展字段
     * 私聊 sourceId 消息来源 
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 扩展字段
     * 私聊 sourceId 消息来源 
     * </pre>
     *
     * <code>optional string ext = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatType_ != 0) {
        output.writeInt32(1, chatType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (!getExtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ext_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chatType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (!getExtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ext_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linlazy.mmorpg.pb.PBModule1Chat.PushChat)) {
        return super.equals(obj);
      }
      com.linlazy.mmorpg.pb.PBModule1Chat.PushChat other = (com.linlazy.mmorpg.pb.PBModule1Chat.PushChat) obj;

      boolean result = true;
      result = result && (getChatType()
          == other.getChatType());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getExt()
          .equals(other.getExt());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linlazy.mmorpg.pb.PBModule1Chat.PushChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *推送聊天信息
     * </pre>
     *
     * Protobuf type {@code PushChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushChat)
        com.linlazy.mmorpg.pb.PBModule1Chat.PushChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_PushChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_PushChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.class, com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.Builder.class);
      }

      // Construct using com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chatType_ = 0;

        content_ = "";

        ext_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.internal_static_PushChat_descriptor;
      }

      public com.linlazy.mmorpg.pb.PBModule1Chat.PushChat getDefaultInstanceForType() {
        return com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.getDefaultInstance();
      }

      public com.linlazy.mmorpg.pb.PBModule1Chat.PushChat build() {
        com.linlazy.mmorpg.pb.PBModule1Chat.PushChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linlazy.mmorpg.pb.PBModule1Chat.PushChat buildPartial() {
        com.linlazy.mmorpg.pb.PBModule1Chat.PushChat result = new com.linlazy.mmorpg.pb.PBModule1Chat.PushChat(this);
        result.chatType_ = chatType_;
        result.content_ = content_;
        result.ext_ = ext_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linlazy.mmorpg.pb.PBModule1Chat.PushChat) {
          return mergeFrom((com.linlazy.mmorpg.pb.PBModule1Chat.PushChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linlazy.mmorpg.pb.PBModule1Chat.PushChat other) {
        if (other == com.linlazy.mmorpg.pb.PBModule1Chat.PushChat.getDefaultInstance()) return this;
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getExt().isEmpty()) {
          ext_ = other.ext_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linlazy.mmorpg.pb.PBModule1Chat.PushChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linlazy.mmorpg.pb.PBModule1Chat.PushChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int chatType_ ;
      /**
       * <pre>
       *聊天类型 ，私聊，世界，系统，公会，组队，附近
       * </pre>
       *
       * <code>optional int32 chatType = 1;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <pre>
       *聊天类型 ，私聊，世界，系统，公会，组队，附近
       * </pre>
       *
       * <code>optional int32 chatType = 1;</code>
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *聊天类型 ，私聊，世界，系统，公会，组队，附近
       * </pre>
       *
       * <code>optional int32 chatType = 1;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ext_ = "";
      /**
       * <pre>
       * 扩展字段
       * 私聊 sourceId 消息来源 
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public java.lang.String getExt() {
        java.lang.Object ref = ext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 sourceId 消息来源 
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        java.lang.Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 sourceId 消息来源 
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public Builder setExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ext_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 sourceId 消息来源 
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public Builder clearExt() {
        
        ext_ = getDefaultInstance().getExt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * 私聊 sourceId 消息来源 
       * </pre>
       *
       * <code>optional string ext = 3;</code>
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ext_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PushChat)
    }

    // @@protoc_insertion_point(class_scope:PushChat)
    private static final com.linlazy.mmorpg.pb.PBModule1Chat.PushChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linlazy.mmorpg.pb.PBModule1Chat.PushChat();
    }

    public static com.linlazy.mmorpg.pb.PBModule1Chat.PushChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushChat>
        PARSER = new com.google.protobuf.AbstractParser<PushChat>() {
      public PushChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PushChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushChat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushChat> getParserForType() {
      return PARSER;
    }

    public com.linlazy.mmorpg.pb.PBModule1Chat.PushChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqSendChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqSendChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/mudule1chat.proto\"=\n\013ReqSendChat" +
      "\022\020\n\010chatType\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\022\013\n\003e" +
      "xt\030\003 \001(\t\":\n\010PushChat\022\020\n\010chatType\030\001 \001(\005\022\017" +
      "\n\007content\030\002 \001(\t\022\013\n\003ext\030\003 \001(\t*?\n\tClientCm" +
      "d\022\026\n\022ChatClientCmd_NONE\020\000\022\032\n\026ChatClientC" +
      "md_SendChat\020\001*C\n\rChatServerCmd\022\026\n\022ChatSe" +
      "rverCmd_NONE\020\000\022\032\n\026ChatServerCmd_PushChat" +
      "\020\001*#\n\013InternalCmd\022\024\n\020InternalCmd_NONE\020\000B" +
      "&\n\025com.linlazy.mmorpg.pbB\rPBModule1Chatb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ReqSendChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqSendChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqSendChat_descriptor,
        new java.lang.String[] { "ChatType", "Content", "Ext", });
    internal_static_PushChat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PushChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushChat_descriptor,
        new java.lang.String[] { "ChatType", "Content", "Ext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
