// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/modules.proto

package com.linlazy.mmorpg.pb;

public final class PBModule {
  private PBModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Module}
   */
  public enum Module
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>CHAT = 1;</code>
     */
    CHAT(1),
    /**
     * <code>EMAIL = 2;</code>
     */
    EMAIL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>CHAT = 1;</code>
     */
    public static final int CHAT_VALUE = 1;
    /**
     * <code>EMAIL = 2;</code>
     */
    public static final int EMAIL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Module valueOf(int value) {
      return forNumber(value);
    }

    public static Module forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return CHAT;
        case 2: return EMAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Module> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Module>() {
            public Module findValueByNumber(int number) {
              return Module.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.linlazy.mmorpg.pb.PBModule.getDescriptor().getEnumTypes().get(0);
    }

    private static final Module[] VALUES = values();

    public static Module valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Module(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Module)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/modules.proto*\'\n\006Module\022\010\n\004NONE\020" +
      "\000\022\010\n\004CHAT\020\001\022\t\n\005EMAIL\020\002B!\n\025com.linlazy.mm" +
      "orpg.pbB\010PBModuleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
